[project]
name = "ece-bigdata-2026-fall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Houyem JOUINI", email = "houyem.jouini09@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.6",
    "faker>=40.37.0",
]

[project.scripts]
dataset-users = "ece_bigdata_2026_fall.dataset_users:main"
dataset-orders = "ece_bigdata_2026_fall.dataset_orders:main"
orders-report = "ece_bigdata_2026_fall.orders_report:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
